### STAGE 1: Build ###

#Nous determinons notre scène  builder
FROM node:lts-alpine as builder

COPY package.json package-lock.json ./

RUN npm set progress=false && npm config set depth 0 && npm cache clean --force

##Eviter les installion unitile de npm

RUN npm i && mkdir /slack && cp -R ./node_modules ./slack

WORKDIR /sclack

COPY . .

## Build the angular app in production mode and store the artifacts in dist folder
RUN npm run build.prod.aot


### STAGE 2: Setup ###
FROM nginx:stable-alpine

## Copy our default nginx config
COPY nginx/default.conf /etc/nginx/conf.d/

## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

## From 'builder' stage copy over the artifacts in dist folder to default nginx public folder
COPY --from=builder /slack/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]

